import { DefaultMaterialProps, TextureItem, TEXTURES } from 'type';

  export const texturesSamples: Record<string, { title: string; items: TextureItem[] }> = {
  fabric: {
    title: 'Fabric',
    items: [
      {
        title: 'Default',
        slug: TEXTURES.Reset,
        image: '/textureSample/reset.webp',
        repeat: { x: 0, y: 0 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },

      // disabled by task
      // {
      //   title: 'Book',
      //   slug: TEXTURES.Book_pattern,
      //   image: '/textureSample/fabric/book_pattern.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: true, rough: true },
      // materialDefaults: {...DefaultMaterial},
      // },
      {
        title: 'Brown leather',
        slug: TEXTURES.Brown_leather,
        image: '/textureSample/fabric/brown_leather.png',
        repeat: { x: 3, y: 3 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Denim fabric 01',
        slug: TEXTURES.Denim_fabric,
        image: '/textureSample/fabric/denim_fabric.png',
        repeat: { x: 3, y: 3 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Denim fabric 02',
        slug: TEXTURES.Denim_fabric_02,
        image: '/textureSample/fabric/denim_fabric_02.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Fabric leather 01',
        slug: TEXTURES.Fabric_leather_01,
        image: '/textureSample/fabric/fabric_leather_01.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Fabric leather 02',
        slug: TEXTURES.Fabric_leather_02,
        image: '/textureSample/fabric/fabric_leather_02.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      // disabled by task
      // {
      //   title: 'Fabric',
      //   slug: TEXTURES.Fabric_pattern_05,
      //   image: '/textureSample/fabric/fabric_pattern_05.png',
      //   repeat: { x: 4, y: 4 },
      //   materialUse: { normal: true, rough: true },
      //   materialDefaults: {...DefaultMaterialProps},
      // },
      // disabled by task
      // {
      //   title: 'Fabric 02',
      //   slug: TEXTURES.Fabric_pattern_07,
      //   image: '/textureSample/fabric/fabric_pattern_07.png',
      //   repeat: { x: 4, y: 4 },
      //   materialUse: { normal: true, rough: true },
      //  materialDefaults: {...DefaultMaterial},
      // },
      {
        title: 'Red leather',
        slug: TEXTURES.Leather_red_03,
        image: '/textureSample/fabric/leather_red_02.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Red leather 02',
        slug: TEXTURES.Leather_red_02,
        image: '/textureSample/fabric/leather_red_03.png',
        repeat: { x: 4, y: 4 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'White leather',
        slug: TEXTURES.Leather_white,
        image: '/textureSample/fabric/leather_white.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
    ],
  },
  metal: {
    title: 'Metal',
    items: [
      // disabled by task
      // {
      //   title: 'Factory Wall',
      //   slug: TEXTURES.Factory_wall,
      //   image: '/textureSample/metal/factory_wall.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: true, rough: true },
      //   materialDefaults: {normal: 1, roughness: 0, metalness: 100},
      // },
      // {
      //   title: 'Metal Plate',
      //   slug: TEXTURES.Metal_plate,
      //   image: '/textureSample/metal/metal_plate.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: true, rough: true },
      //   materialDefaults: {normal: 1, roughness: 50, metalness: 45},
      // },
      // {
      //   title: 'Metal Rust',
      //   slug: TEXTURES.Metal_rust,
      //   image: '/textureSample/metal/metal_rust.png',
      //   repeat: { x: 3, y: 3 },
      //   materialUse: { normal: true, rough: true },
      //   materialDefaults: {normal: 1, roughness: 45, metalness: 45},
      // },
      // {
      //   title: 'Rust Coarse',
      //   slug: TEXTURES.Rust_coarse,
      //   image: '/textureSample/metal/rust_coarse.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: true, rough: true },
      //   materialDefaults: {normal: 1, roughness: 0, metalness: 100},
      // },
      {
        title: 'Rusty Metal',
        slug: TEXTURES.Rusty_metal,
        image: '/textureSample/metal/rusty_metal.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { normal: 1, roughness: 0, metalness: 100 },
      },
      // disabled by task
      // {
      //   title: 'Rusty Metal 2',
      //   slug: TEXTURES.Rusty_metal_02,
      //   image: '/textureSample/metal/rusty_metal_02.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: true, rough: true },
      //   materialDefaults: {normal: 1, roughness: 0, metalness: 100},
      // },
    ],
  },
  patterns: {
    title: 'Patterns',
    items: [
      {
        title: 'Digital Camouflage',
        slug: TEXTURES.Digital_camouflage,
        image: '/textureSample/patterns/digital_camouflage.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: false, rough: false },
        materialDefaults: { ...DefaultMaterialProps },
      },
      // disabled by task
      // {
      //   title: 'Etno Diagonal',
      //   slug: TEXTURES.Etno_diagonal,
      //   image: '/textureSample/patterns/etno_diagonal.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: false, rough: false },
      //   materialDefaults: {...DefaultMaterialProps},
      // },
      // {
      //   title: 'Grapefruits',
      //   slug: TEXTURES.Grapefruits,
      //   image: '/textureSample/patterns/grapefruits.png',
      //   repeat: { x: 3, y: 3 },
      //   materialUse: { normal: false, rough: false },
      //   materialDefaults: {...DefaultMaterialProps},
      // },
      {
        title: 'Forest camouflage',
        slug: TEXTURES.Forest_camouflage,
        image: '/textureSample/patterns/forest_camouflage.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: false, rough: false },
        materialDefaults: { ...DefaultMaterialProps },
      },
      // disabled by task
      // {
      //   title: 'Leafs',
      //   slug: TEXTURES.Leafs,
      //   image: '/textureSample/patterns/leafs.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: false, rough: false },
      //   materialDefaults: {...DefaultMaterialProps},
      // },
      // {
      //   title: 'Roses',
      //   slug: TEXTURES.Roses,
      //   image: '/textureSample/patterns/roses.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: false, rough: false },
      //   materialDefaults: {...DefaultMaterialProps},
      // },
      // {
      //   title: 'Zigzag',
      //   slug: TEXTURES.Zigzag,
      //   image: '/textureSample/patterns/zigzag.png',
      //   repeat: { x: 2, y: 2 },
      //   materialUse: { normal: false, rough: false },
      //   materialDefaults: {...DefaultMaterialProps},
      // },
    ],
  },
  new: {
    title: 'New',
    items: [
      {
        title: 'Canvas',
        slug: TEXTURES.canvas_solid,
        image: '/textureSample/new/canvas_solid.png',
        repeat: { x: 14, y: 14 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Denim',
        slug: TEXTURES.denim_abstract,
        image: '/textureSample/new/denim_abstract.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Fleece',
        slug: TEXTURES.fleece_solid,
        image: '/textureSample/new/fleece_solid.png',
        repeat: { x: 14, y: 14 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'French terry',
        slug: TEXTURES.french_terry_solid,
        image: '/textureSample/new/french_terry_solid.png',
        repeat: { x: 7, y: 7 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Satin solid',
        slug: TEXTURES.satin_solid,
        image: '/textureSample/new/satin_solid.png',
        repeat: { x: 8, y: 8 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { normal: 1, roughness: 70, metalness: 70 },
      },
      {
        title: 'Tweed houndstooth',
        slug: TEXTURES.tweed_houndstooth,
        image: '/textureSample/new/tweed_houndstooth.png',
        repeat: { x: 16, y: 16 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Vegan fur',
        slug: TEXTURES.vegan_fur_solid,
        image: '/textureSample/new/vegan_fur_solid.png',
        repeat: { x: 10, y: 10 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Vegan suede',
        slug: TEXTURES.vegan_suede_solid,
        image: '/textureSample/new/vegan_suede_solid.png',
        repeat: { x: 2, y: 2 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { ...DefaultMaterialProps },
      },
      {
        title: 'Velour',
        slug: TEXTURES.velour_solid,
        image: '/textureSample/new/velour_solid.png',
        repeat: { x: 18, y: 18 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { normal: 1, roughness: 90, metalness: 30 },
      },
      {
        title: 'Velvet',
        slug: TEXTURES.velvet_solid,
        image: '/textureSample/new/velvet_solid.png',
        repeat: { x: 16, y: 16 },
        materialUse: { normal: true, rough: true },
        materialDefaults: { normal: 1, roughness: 90, metalness: 30 },
      },
    ]
  }
};
