import { Product } from 'type';

export const products: Record<string, Product[]> = {
    caps: [
        {
            title: 'Hat1',
            slug: 'caps',
            image: 'models/caps/Hat1/preview.png',
            modelName: 'caps/Hat1/Hat1.gltf',
            mainTexName: 'caps/Hat1/Texture_Hat1/hat1_diffuse_1001.png',
            modelScale: 0.4,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Hat2',
            slug: 'caps',
            image: 'models/caps/Hat2/preview.png',
            modelName: 'caps/Hat2/H2.gltf',
            mainTexName: 'caps/Hat2/Texture_Hat2/Hat2_diffuse_1001.png',
            modelScale: 0.4,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Mesh snapback',
            slug: 'caps',
            image: '/images/cats/Hats/1. Mesh snapback.png',
            modelName: 'caps/Cap 1KG/Cap 1KG.gltf',
            mainTexName: 'caps/Cap 1KG/Cotton_Stretch_Sateen_FRONT_1581_Base_Color 2.jpg',
            modelScale: 2.5,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Classic trucker hat',
            slug: 'caps',
            image: '/images/cats/Hats/2. Classic trucker hat.png',
            modelName: 'caps/Cap ADR/Cap ADR.gltf',
            mainTexName: 'caps/Cap ADR/Cotton_Heavy_Twill_FRONT_1786_Base_Color.jpg',
            modelScale: 2.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Classic Yankee hat',
            slug: 'caps',
            image: '/images/cats/Hats/3. Classic Yankee hat.png',
            modelName: 'caps/Cap Alphaphi Alpha/Cap Alphaphi Alpha.gltf',
            mainTexName: 'caps/Cap Alphaphi Alpha/Cotton_Gabardine_FRONT_1563_Base_Color.jpg',
            modelScale: 2.5,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: 1,
            flipBaseMapX: -1,
        },
        {
            title: 'Classic strapback',
            slug: 'caps',
            image: '/images/cats/Hats/4. Classic strapback.png',
            modelName: 'caps/Cap Arigato/Cap Arigato.glb',
            mainTexName: 'caps/Cap Arigato/Material2186191_Base_Color.jpg',
            modelScale: 2.5,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Classic snapback',
            slug: 'caps',
            image: '/images/cats/Hats/5. Classic snapback.png',
            modelName: 'caps/Cap Balcony Lifestyle/Cap Balcony Lifestyle.gltf',
            mainTexName: 'caps/Cap Balcony Lifestyle/Visor_Base_Color.jpg',
            modelScale: 2.5,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: 1,
        }
    ],
    tees: [
        {
            title: 'No-hems t-shirt',
            slug: 'tees',
            image: '/images/cats/Shirts/1. No-hems t-shirt.png',
            modelName: 'tees/T-shirt/tshirt.gltf',
            mainTexName: 'tees/T-shirt/Tshirt.png',
            modelScale: 1,
            flipBaseMapY: 0,
            offset: {
                x: 0,
                y: 0,
                z: 0.075
            }
        },
        {
            title: 'Boxy oversized t-shirt',
            slug: 'tees',
            image: '/images/cats/Shirts/2. Boxy oversized t-shirt.png',
            modelName: 'tees/Tee1/Tee1.gltf',
            mainTexName: 'tees/Tee1/Tee1_textures/Tee1_diffuse_1001.png',
            modelScale: 0.1,
            flipBaseMapY: -1,
            offset: { x: 0, y: 0, z: 0 }
        },
        {
            title: 'V-neck t-shirt',
            slug: 'tees',
            image: '/images/cats/Shirts/3. V-neck t-shirt.png',
            modelName: 'tees/Tee2/Tee2.gltf',
            mainTexName: 'tees/Tee2/Tee2_textures/Tee2_diffuse_1001.png',
            modelScale: 0.1,
            flipBaseMapY: -1,
            offset: { x: 0, y: 0, z: 0 }
        },
        {
            title: 'Long oversized t-shirt',
            slug: 'tees',
            image: '/images/cats/Shirts/4. Long oversized t-shirt.png',
            modelName: 'tees/T-shirt Barikada White/T-shirt Barikada White.gltf',
            mainTexName: 'tees/T-shirt Barikada White/Knit_Cotton_Jersey_FRONT_6757775_Base_Color.jpg',
            modelScale: 1,
            flipBaseMapY: 1,
            offset: { x: 0, y: 0, z: 0 }
        },
        {
            title: 'Wide neck t-shirt',
            slug: 'tees',
            image: '/images/cats/Shirts/5. Wide neck t-shirt.png',
            modelName: 'tees/T-shirt STRAYA/T-shirt STRAYA.gltf',
            mainTexName: 'tees/T-shirt STRAYA/FABRIC_Base_Color.jpg',
            modelScale: 1,
            flipBaseMapY: -1,
            offset: { x: 0, y: 0, z: 0.1 }
        },
        {
            title: 'Classic polo shirt',
            slug: 'tees',
            image: '/images/cats/Shirts/6. Classic polo shirt.png',
            modelName: 'tees/Polo Rich fantasy/Polo Rich fantasy.gltf',
            mainTexName: 'tees/Polo Rich fantasy/Knit_Cotton_Jersey_FRONT_1676734_Base_Color.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        }
    ],
    sweaters: [
        {
            title: 'Sweater',
            slug: 'sweaters',
            image: 'models/sweaters/Sweater/preview.png',
            modelName: 'sweaters/Sweater/Sweater.gltf',
            mainTexName: 'sweaters/Sweater/Texture/Sweater_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Classic front pocket hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/1. Classic front pocket hoodie.png',
            modelName: 'sweaters/Hoodie FMS/Hoodie FMS2.gltf',
            mainTexName: 'sweaters/Hoodie FMS/Knit_Cotton_Jersey_FRONT_2736812_Base_Color.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Cropped fit hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/2. Cropped fit hoodie.png',
            modelName: 'sweaters/Hoodie Arkyvs/Hoodie Arkyvs.gltf',
            mainTexName: 'sweaters/Hoodie Arkyvs/Rib_1X1_319gsm_FRONT_54582019_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Cropped front pocket hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/3. Cropped front pocket hoodie.png',
            modelName: 'sweaters/Hoodie Black strange/Hoodie Black strange.gltf',
            mainTexName: 'sweaters/Hoodie Black strange/Knit_Cotton_Jersey_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Wide hems hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/4. Wide hems hoodie.png',
            modelName: 'sweaters/Hoodie Dapadrone/Hoodie Dapadrone.gltf',
            mainTexName: 'sweaters/Hoodie Dapadrone/Rib_1X1_319gsm_FRONT_43574426_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'No-hem hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/5. No-hem hoodie.png',
            modelName: 'sweaters/Hoodie GAS/Hoodie GAS.gltf',
            mainTexName: 'sweaters/Hoodie GAS/(A)SwatchOn_QL-019555_Velvet_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: 1,
        },
        {
            title: 'Zip-up hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/6. Zip-up hoodie.png',
            modelName: 'sweaters/Hoodie Nate Washed Effect/Hoodie Nate Washed Effect.gltf',
            mainTexName: 'sweaters/Hoodie Nate Washed Effect/DefaultMaterial_Base_Color2.jpg',
            modelScale: 0.9,
            offset: { x: 0, y: -1.4, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Drawstrings bulky hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/7. Drawstrings bulky hoodie.png',
            modelName: 'hoodies/Hoodie Nike Drake/Hoodie Nike Drake.gltf',
            mainTexName: 'hoodies/Hoodie Nike Drake/Knit_Fleece_Terry_FRONT_13945931_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: 1,
        },
        {
            title: 'Zip-up wide hem hoodie',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/8. Zip-up wide hem hoodie.png',
            modelName: 'hoodies/Hoodie Trapstar/Hoodie Trapstar.gltf',
            mainTexName: 'hoodies/Hoodie Trapstar/DefaultMaterial_Base_Color2.jpg',
            modelScale: 0.9,
            offset: { x: 0, y: -1.3, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Loose fit longsleeve',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/9. Loose fit longsleeve.png',
            modelName: 'hoodies/Sweatshirt Jungle/Sweatshirt Jungle.gltf',
            mainTexName: 'hoodies/Sweatshirt Jungle/Cotton_Sateen_Base_Color 2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Classic sweatshirt',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/10. Classic sweatshirt.png',
            modelName: 'hoodies/Sweatshirt Melange RISCA/Sweatshirt Melange RISCA.gltf',
            mainTexName: 'hoodies/Sweatshirt Melange RISCA/FABRIC_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Fitted hem sweatshirt',
            slug: 'sweaters',
            image: '/images/cats/Hoodies/11. Fitted hem sweatshirt.png',
            modelName: 'hoodies/Sweetshot/Sweetshot.gltf',
            mainTexName: 'hoodies/Sweetshot/Sweetshot_textures/Sweetshot_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        }
    ],
    pants: [
        {
            title: 'Cargo',
            slug: 'pants',
            image: 'models/pants/Cargo/preview.png',
            modelName: 'pants/Cargo/Cargo22.gltf',
            mainTexName: 'pants/Cargo/Texture/Cargo_diffuse_1001.png',
            modelScale: 0.09,
            offset: { x: 0, y: 0.7, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Leggins',
            slug: 'pants',
            image: 'models/pants/Leggins/preview.png',
            modelName: 'pants/Leggins/Leggins.gltf',
            mainTexName: 'pants/Leggins/Texture/Leggins_diffuse_1001.png',
            modelScale: 0.09,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Leggins 2',
            slug: 'pants',
            image: 'models/pants/Leggins2/preview.png',
            modelName: 'pants/Leggins2/Leggins2.gltf',
            mainTexName: 'pants/Leggins2/Texture/Leggins2_diffuse_1001.png',
            modelScale: 0.09,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Jeans_female',
            slug: 'pants',
            image: 'models/pants/Jeans_female/preview.png',
            modelName: 'pants/Jeans_female/Jeans Female 22.gltf',
            mainTexName: 'pants/Jeans_female/Texture/Jeans_female1_diffuse_1001.png',
            modelScale: 0.09,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Jeans_male',
            slug: 'pants',
            image: 'models/pants/Jeans_male/preview.png',
            modelName: 'pants/Jeans_male/Jeans_male22.gltf',
            mainTexName: 'pants/Jeans_male/Texture/Jeans_male1_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Classic sweatpants',
            slug: 'pants',
            image: 'images/cats/Pants/1. Classic sweatpants.png',
            modelName: 'pants/Pants/Pants.gltf',
            mainTexName: 'pants/Pants/Pants_texture/Pants_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        }
    ],
    tops:[
        {
            title: 'Top Female',
            slug: 'tops',
            image: 'models/tops/Top female/preview.png',
            modelName: 'tops/Top female/Top Female.gltf',
            mainTexName: 'tops/Top female/Texture/Top Female_diffuse_1001.png',
            modelScale: 0.15,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Top Female 2',
            slug: 'tops',
            image: 'models/tops/Top female2/preview.png',
            modelName: 'tops/Top female2/Top female2.gltf',
            mainTexName: 'tops/Top female2/Texture/Top female2_diffuse_1001.png',
            modelScale: 0.15,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Top Female 3',
            slug: 'tops',
            image: 'models/tops/Top female3/preview.png',
            modelName: 'tops/Top female3/Top female3.gltf',
            mainTexName: 'tops/Top female3/Texture/Top female3_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Top Female 4',
            slug: 'tops',
            image: 'models/tops/Top female4/preview.png',
            modelName: 'tops/Top female4/Top female4.gltf',
            mainTexName: 'tops/Top female4/Texture/Top female4_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0.9, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Top Female 5',
            slug: 'tops',
            image: 'models/tops/Top female5/preview.png',
            modelName: 'tops/Top female5/Top Female5.gltf',
            mainTexName: 'tops/Top female5/Texture/Top Female5_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Top Male',
            slug: 'tops',
            image: 'models/tops/Top Male/preview.png',
            modelName: 'tops/Top Male/Top Male.gltf',
            mainTexName: 'tops/Top Male/Texture/Top Male_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Top Male 2',
            slug: 'tops',
            image: 'models/tops/Top Male2/preview.png',
            modelName: 'tops/Top Male2/Top Male2.gltf',
            mainTexName: 'tops/Top Male2/Texture/Top Male2_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
    ],
    dress:[
        {
            title: 'Long Dress',
            slug: 'dresses',
            image: 'models/dresses/Long Dress/preview.png',
            modelName: 'dresses/Long Dress/Long Dress.gltf',
            mainTexName: 'dresses/Long Dress/Texture/Long Dress_diffuse_1001.png',
            modelScale: 0.07,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Long Dress 2',
            slug: 'dresses',
            image: 'models/dresses/Long Dress2/preview.png',
            modelName: 'dresses/Long Dress2/Long Dress2.gltf',
            mainTexName: 'dresses/Long Dress2/Texture/LongDress2_diffuse_1001.png',
            modelScale: 0.07,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Midi dress',
            slug: 'dresses',
            image: 'models/dresses/Midi dress/preview.png',
            modelName: 'dresses/Midi dress/Midi Dress.gltf',
            mainTexName: 'dresses/Midi dress/Texture/Midi Dress_diffuse_1001.png',
            modelScale: 0.07,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Midi Skirt',
            slug: 'dresses',
            image: 'models/dresses/Midi Skirt/preview.png',
            modelName: 'dresses/Midi Skirt/Midi Skirt.gltf',
            mainTexName: 'dresses/Midi Skirt/Texture/Midi Skirt_diffuse_1001.png',
            modelScale: 0.07,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Mini Skirt',
            slug: 'dresses',
            image: 'models/dresses/Mini Skirt/preview.png',
            modelName: 'dresses/Mini Skirt/Mini Skirt.gltf',
            mainTexName: 'dresses/Mini Skirt/Texture/Mini Skirt_diffuse_1001.png',
            modelScale: 0.07,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
    ],
    jackets:[
        {
          title: 'Bomber',
          slug: 'jackets',
          image: 'models/jackets/Bomber/preview.png',
          modelName: 'jackets/Bomber/Bomber.gltf',
          mainTexName: 'jackets/Bomber/Texture/Bomber_diffuse_1001.png',
          modelScale: 0.1,
          offset: { x: 0, y: 0, z: 0 },
          flipBaseMapY: -1,
        },
        {
          title: 'Leather Jacket',
          slug: 'jackets',
          image: 'models/jackets/Leather Jacket/preview.png',
          modelName: 'jackets/Leather Jacket/Leather Jacket.gltf',
          mainTexName: 'jackets/Leather Jacket/Texture/LeatherJacket_diffuse_1001.png',
          modelScale: 0.1,
          offset: { x: 0, y: 0, z: 0 },
          flipBaseMapY: -1,
        },
        {
            title: 'Bomber jacket',
            slug: 'jackets',
            image: '/images/cats/Hoodies/12. Bomber jacket.png',
            modelName: 'jackets/Bomber Ricco Giovente/Bomber Ricco Giovente.gltf',
            mainTexName: 'jackets/Bomber Ricco Giovente/base_FRONT_57368459_Base_Color2.jpg',
            modelScale: 1.0,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Jacket-Skirt',
            slug: 'jackets',
            image: 'models/jackets/Jacket-Skirt/preview.png',
            modelName: 'jackets/Jacket-Skirt/Jacket-Skirt.gltf',
            mainTexName: 'jackets/Jacket-Skirt/Texture/Jacket-Skirt_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Puffer',
            slug: 'jackets',
            image: 'models/jackets/Puffer/preview.png',
            modelName: 'jackets/Puffer/Puffer22.gltf',
            mainTexName: 'jackets/Puffer/Texture/Puffer_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0.7, z: 0 },
            flipBaseMapY: -1,
        },
    ],
    shorts:[
        {
            title: 'Drawstrings long shorts',
            slug: 'shorts',
            image: 'images/cats/Pants/2. Drawstrings long shorts.png',
            modelName: 'shorts/Shorts1/Shorts1.gltf',
            mainTexName: 'shorts/Shorts1/Shorts1/Shorts1_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Sporty shorts',
            slug: 'shorts',
            image: 'images/cats/Pants/3. Sporty shorts.png',
            modelName: 'shorts/Shorts2/Shorts2.gltf',
            mainTexName: 'shorts/Shorts2/Shorts2_texture/Shorts2_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Shorts',
            slug: 'shorts',
            image: 'models/shorts/Shorts/preview.png',
            modelName: 'shorts/Shorts/Shorts.gltf',
            mainTexName: 'shorts/Shorts/Texture/Shorts_diffuse_1001.png',
            modelScale: 0.1,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
    ],
    shirts:[
        {
            title: 'Shirt Male 2',
            slug: 'shirts',
            image: 'models/shirts/Shirt Male2/preview.png',
            modelName: 'shirts/Shirt Male2/Shirt Male2.gltf',
            mainTexName: 'shirts/Shirt Male2/texture/Shirt Male2_diffuse_1001.png',
            modelScale: 0.1,
            flipBaseMapY: 0,
            offset: { x: 0, y: 0, z: 0 }
        },
        {
            title: 'Shirt Male',
            slug: 'shirts',
            image: 'models/shirts/Shirt_Male/preview.png',
            modelName: 'shirts/Shirt_Male/Shirt Male1.gltf',
            mainTexName: 'shirts/Shirt_Male/Texture/Shirt Male1_diffuse_1001.png',
            modelScale: 0.1,
            flipBaseMapY: 0,
            offset: { x: 0, y: 0, z: 0 }
        },
    ],
    other: [
        {
            title: 'Tote bag',
            slug: 'other',
            image: 'images/cats/Accessories/1. Tote bag.png',
            modelName: 'other/Bag/Bag.gltf',
            mainTexName: 'other/Bag/Textures_Bag/Bag_diffuse_1001.png',
            modelScale: 0.12,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        },
        {
            title: 'Socks',
            slug: 'other',
            image: 'images/cats/Accessories/2. Socks.png',
            modelName: 'other/Socks/Socks.gltf',
            mainTexName: 'other/Socks/Textures_Socks/Socks_diffuse_1001.png',
            modelScale: 0.2,
            offset: { x: 0, y: 0, z: 0 },
            flipBaseMapY: -1,
        }
    ],
};
